### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by probdg** [sadigitID/affiliate-system-sadigit#2]

**Comment by salrnazizah** [comment]
> @probdg izin bertanya kak, yg dimaksud snapshot itu yg bagaimana ya? kalian boleh cari aja referensi di google , kasus nya sudah di kasih seperti di contoh . terus itu kenapa tiap tabel di tambah huruf s di akhir nya?

Huruf s itu ditambah agar jamak kak

**Comment by probdg** [comment]
Iya boleh jamak tapi harus di barengi juga dengan bahasa inggris , ini di bahasa indonesia di tambah huruf s , kalau users boleh , perbaiki lagi kalau mau gunakan bahasa   indonesia saja

**Comment by salrnazizah** [comment]
> Iya boleh jamak tapi harus di barengi juga dengan bahasa inggris , ini di bahasa indonesia di tambah huruf s , kalau users boleh , perbaiki lagi kalau mau gunakan bahasa indonesia saja

baik ka, sudah diperbaiki untuk nama tabelnya

**Comment by probdg** [comment]
👍 okey lanjutkan
