### ISSUE TITLE
Modul Bonus

### ISSUE THREAD

**Issue by probdg** [sadigitID/affiliate-system-sadigit#5]
@Risnaber  @salrnazizah  @Rochmadiar 
Bagian nama user di buat select sesuai dengan users yang daftar 
![Screenshot from 2022-08-23 17-00-10](https://user-images.githubusercontent.com/17420498/186131135-6dd47229-75c6-4b95-af51-1e56a855a39a.png)

Yang mengerjakan bagian Modul Bonus perbaiki lagi yang membut tidak refresh table itu karena di ganti draw => 1
![Screenshot from 2022-08-23 17-00-02](https://user-images.githubusercontent.com/17420498/186131274-f5d660cb-02c1-498e-832a-7c379e59dbcd.png)

di buat TRUE saja bagian prosessing nya dan harus method POST 
![Screenshot from 2022-08-23 17-03-43](https://user-images.githubusercontent.com/17420498/186131475-94a1d6fd-4da1-46ab-b622-89ac7bd24549.png)

Sudah di bagian depan ini tidak perlu flash data lagi 
![Screenshot from 2022-08-23 16-59-27](https://user-images.githubusercontent.com/17420498/186131674-bbf48edf-c9ab-447c-86ef-0a19dd6238f4.png)

Kalian Pelajari lagi ajax JQuery nya dan Javascript

**Comment by salrnazizah** [comment]
baik ka sudah direvisi tapi masih ada kendala di bagian select nama affiliator

**Comment by probdg** [comment]
Sama dengan buat propinsi, kabupaten, kecamatan

**Comment by salrnazizah** [comment]
baik ka sedang saya coba dan usahakan

**Comment by RisnaBerti** [comment]
Ka untuk yang select provinsi, kabupaten, kecamatan belum bisa muncul
saya udh nyari tutor dan referensi lain dan mengganti beberapa versi jquery ttp tidak mau muncul ka
tolong solusinya, Terimakasih

**Comment by salrnazizah** [comment]
yg dibagian input bonus memasukkan nama user berdasarkan yang daftar itu sudah muncul dengan join tabel dan dgn menggunakan referensi yg diberi diwhatsapp tapi tetep masih ada kesalahan logika ka jadi saya membantu mengerjakan yang select provinsi, kabupaten, dan kecamatan dulu dan jg menggunakan referensi lain ka tapi tetep tidak mau muncul
